import { ArrowLeft, BarChart3, CalendarClock, ExternalLink, Link2, ListChecks, Pencil, QrCode } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { BusinessLogo } from "@/features/businesses/business-logo";
import { BusinessStatusActions } from "@/features/businesses/business-status-actions";
import { getBusinessById } from "@/features/businesses/queries";
import { getBusinessLogoUrl } from "@/features/businesses/storage";
import { BusinessStatusBadge } from "@/features/businesses/status-badge";
import { normalizeGoogleMapsUrl } from "@/features/businesses/schemas";
import { getCurrentSubscriptionsByBusinessIds } from "@/features/subscriptions/queries";
import { SubscriptionStatusBadge } from "@/features/subscriptions/subscription-status-badge";
import { formatNepalDateTime, getExpiringLabel, getSubscriptionTiming } from "@/features/subscriptions/utils";
import { evaluateBusinessAvailability } from "@/server/services/business-availability";
import { getQuestionSummary } from "@/features/review-questions/queries";
import { serverEnv } from "@/lib/env/server";
import { requireAdminPage } from "@/lib/auth/admin";
import { buildBusinessReviewUrl } from "@/lib/urls/business-review";
import { getBusinessAnalytics } from "@/features/analytics/queries";
import { getAnalyticsDateRange } from "@/features/analytics/date-range";
import { getSmartLinksAdmin } from "@/features/smart-links/queries";

export default async function BusinessDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requireAdminPage();
  const { id } = await params;
  const { business, supabase } = await getBusinessById(id);
  if (!business) notFound();
  const smartLinks = await getSmartLinksAdmin(business.id);
  const [subscriptions, questionSummary, recentAnalytics] = await Promise.all([getCurrentSubscriptionsByBusinessIds([business.id]), getQuestionSummary(business.id), getBusinessAnalytics(business.id, getAnalyticsDateRange({ range: "30d" }))]);
  const subscription = subscriptions.get(business.id) ?? null;
  const timing = getSubscriptionTiming(subscription);
  const availability = evaluateBusinessAvailability(business.status, subscription);
  const expiringLabel = getExpiringLabel(timing.expiringWindow);
  const googleMapsUrl = normalizeGoogleMapsUrl(business.google_review_url);
  let publicUrl: string | null = null;
  try { publicUrl = buildBusinessReviewUrl(business.slug, serverEnv.NEXT_PUBLIC_APP_URL); } catch { /* QR card shows configuration state. */ }
  return <div className="mx-auto max-w-3xl">
    <Link className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-slate-600 hover:text-slate-950" href="/admin/businesses"><ArrowLeft className="size-5" /> Businesses</Link>
    <section className="mt-3 rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-start gap-4"><BusinessLogo alt={business.name} color={business.primary_color} size="lg" url={getBusinessLogoUrl(supabase, business.logo_path)} /><div className="min-w-0 flex-1"><BusinessStatusBadge status={business.status} /><h1 className="mt-3 break-words text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">{business.name}</h1>{business.description ? <p className="mt-2 text-sm leading-6 text-slate-600">{business.description}</p> : null}</div></div><Link className="mt-6 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-slate-900 px-4 text-sm font-semibold text-white" href={`/admin/businesses/${business.id}/edit`}><Pencil className="size-4" /> Edit profile</Link></section>
    <section className="mt-5 rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">Subscription</p><h2 className="mt-2 text-lg font-semibold text-slate-950">{subscription?.plan ?? "Not configured"}</h2></div><SubscriptionStatusBadge subscription={subscription} /></div>{subscription ? <div className="mt-4"><p className="text-sm text-slate-600">Expires {formatNepalDateTime(subscription.expires_at)}</p><p className={`mt-1 text-xs font-medium ${availability.valid ? "text-emerald-700" : "text-amber-700"}`}>{availability.valid ? "Business access available" : `Unavailable — ${availability.reason.toLowerCase().replaceAll("_", " ")}`}{expiringLabel ? ` · ${expiringLabel}` : ""}</p></div> : <p className="mt-3 text-sm text-slate-500">No subscription configured.</p>}<Link className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-emerald-700 px-4 text-sm font-semibold text-white hover:bg-emerald-800" href={`/admin/businesses/${business.id}/subscription`}><CalendarClock className="size-5" /> Manage subscription</Link></section>
    <section className="mt-5 rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-2xl bg-sky-100 text-sky-700"><ListChecks className="size-5" /></span><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">Review questions</p><h2 className="mt-1 text-lg font-semibold text-slate-950">{questionSummary.active} active · {questionSummary.total} total</h2></div></div><Link className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-slate-900 px-4 text-sm font-semibold text-white" href={`/admin/businesses/${business.id}/questions`}><ListChecks className="size-5" /> Manage questions</Link></section>
    <section className="mt-5 rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-2xl bg-emerald-100 text-emerald-700"><QrCode className="size-5" /></span><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">Review QR</p><h2 className="mt-1 text-lg font-semibold text-slate-950">{publicUrl ? "Ready to use" : "Configuration needed"}</h2></div></div><p className="mt-3 break-all text-sm leading-6 text-slate-500">{publicUrl ?? "Configure NEXT_PUBLIC_APP_URL before generating QR assets."}</p><Link className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-emerald-700 px-4 text-sm font-semibold text-white" href={`/admin/businesses/${business.id}/qr`}><QrCode className="size-5" />View Review QR</Link></section>
    <section className="mt-5 rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-2xl bg-violet-100 text-violet-700"><BarChart3 className="size-5" /></span><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">Last 30 days</p><h2 className="mt-1 text-lg font-semibold text-slate-950">Analytics</h2></div></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-2xl font-semibold text-slate-950">{recentAnalytics.events.page_views}</p><p className="mt-1 text-xs text-slate-500">Page views</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-2xl font-semibold text-slate-950">{recentAnalytics.events.google_handoffs}</p><p className="mt-1 text-xs text-slate-500">Google handoffs</p></div></div><Link className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-slate-900 px-4 text-sm font-semibold text-white" href={`/admin/businesses/${business.id}/analytics`}><BarChart3 className="size-5" />View Analytics</Link></section>
    <section className="mt-5 rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-lg font-semibold text-slate-950">Links</h2><div className="mt-4 space-y-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Public review URL</p>{publicUrl ? <a className="mt-1 flex items-center gap-2 break-all text-sm font-medium text-emerald-700" href={publicUrl} rel="noreferrer" target="_blank"><Link2 className="size-4 shrink-0" />{publicUrl}</a> : <p className="mt-1 text-sm text-amber-700">Public URL configuration is invalid.</p>}</div><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Google Maps Link</p>{googleMapsUrl ? <a className="mt-2 inline-flex min-h-10 items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-3 text-sm font-semibold text-emerald-800" href={googleMapsUrl} rel="noreferrer" target="_blank">Test link<ExternalLink className="size-4" /></a> : <p className="mt-2 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Add a valid Google Maps link before sending customers to Google.</p>}</div></div></section>
    <section className="mt-5 rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-lg font-semibold text-slate-950">Smart Links QR</h2><p className="mt-2 text-sm text-slate-500">{smartLinks.length} configured · {smartLinks.filter(link => link.is_active).length} active</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Link className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-emerald-700 px-4 text-sm font-semibold text-white" href={`/admin/businesses/${business.id}/smart-qr`}><QrCode className="size-5" />View Smart QR</Link><Link className="flex min-h-12 items-center justify-center rounded-2xl bg-slate-900 px-4 text-sm font-semibold text-white" href={`/admin/businesses/${business.id}/smart-links`}>Manage Smart Links</Link></div></section>
    <section className="mt-5 rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-lg font-semibold text-slate-950">Availability</h2><BusinessStatusActions businessId={business.id} status={business.status} /></section>
  </div>;
}
