"use client";

import { Archive, ChevronDown, ChevronUp, LoaderCircle, Pencil, Plus, Sparkles, X } from "lucide-react";
import { useActionState, useState } from "react";

import { manageOptionAction, manageQuestionAction, type ReviewActionState } from "@/features/review-questions/actions";
import { optionValueFromLabel } from "@/features/review-questions/schemas";
import type { Tables } from "@/types/database";

type Option = Tables<"review_question_options">;
type Question = Tables<"review_questions"> & { options: Option[] };
type QuestionDialog = { mode: "create" } | { mode: "edit"; question: Question };
type OptionDialog = { mode: "create"; questionId: string } | { mode: "edit"; questionId: string; option: Option };
const initialState: ReviewActionState = {};

function Hidden({ name, value }: { name: string; value: string | number | boolean }) { return <input name={name} type="hidden" value={String(value)} />; }

export function QuestionManager({ businessId, questions }: { businessId: string; questions: Question[] }) {
  const [questionState, questionAction, questionPending] = useActionState(manageQuestionAction, initialState);
  const [optionState, optionAction, optionPending] = useActionState(manageOptionAction, initialState);
  const [questionDialog, setQuestionDialog] = useState<QuestionDialog | null>(null);
  const [optionDialog, setOptionDialog] = useState<OptionDialog | null>(null);
  const [archiveQuestion, setArchiveQuestion] = useState<Question | null>(null);
  const [optionLabel, setOptionLabel] = useState("");
  const [optionValue, setOptionValue] = useState("");
  const [valueEdited, setValueEdited] = useState(false);

  const error = questionState.error ?? optionState.error;
  const compactButton = "flex size-10 items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-600 disabled:opacity-30";

  function openOption(dialog: OptionDialog) {
    setOptionDialog(dialog);
    setOptionLabel(dialog.mode === "edit" ? dialog.option.label : "");
    setOptionValue(dialog.mode === "edit" ? dialog.option.value : "");
    setValueEdited(dialog.mode === "edit");
  }

  return <div>
    {error ? <p className="mb-4 rounded-2xl bg-rose-50 p-4 text-sm text-rose-700" role="alert">{error}</p> : null}
    {!questions.length ? <section className="rounded-[1.75rem] border border-dashed border-slate-300 bg-white p-6 text-center shadow-sm sm:p-10"><span className="mx-auto flex size-14 items-center justify-center rounded-2xl bg-emerald-100 text-emerald-700"><Sparkles className="size-7" /></span><h2 className="mt-4 text-lg font-semibold text-slate-950">Start with three recommended questions</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">Create the editable starter template, or add your own question.</p><form action={questionAction} className="mt-5"><Hidden name="action" value="CREATE_DEFAULTS" /><Hidden name="businessId" value={businessId} /><button className="min-h-12 rounded-2xl bg-emerald-700 px-5 text-sm font-semibold text-white" disabled={questionPending}>Create recommended set</button></form><button className="mt-3 min-h-11 text-sm font-semibold text-slate-600" onClick={() => setQuestionDialog({ mode: "create" })} type="button">Add one question instead</button></section> : <div className="space-y-4">{questions.map((question, index) => {
      const activeOptions = question.options.filter((option) => option.is_active).length;
      return <article className="rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm" key={question.id}>
        <div className="flex items-start gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-sm font-semibold text-slate-600">{index + 1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><h2 className="font-semibold leading-6 text-slate-950">{question.question}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${question.is_active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{question.is_active ? "Active" : "Inactive"}</span></div><p className="mt-1 text-xs text-slate-500">{activeOptions} active · {question.options.length} total options</p></div></div>
        <div className="mt-4 flex flex-wrap items-center gap-2"><form action={questionAction}><Hidden name="action" value="MOVE" /><Hidden name="businessId" value={businessId} /><Hidden name="questionId" value={question.id} /><Hidden name="direction" value="UP" /><button aria-label="Move question up" className={compactButton} disabled={index === 0 || questionPending}><ChevronUp className="size-5" /></button></form><form action={questionAction}><Hidden name="action" value="MOVE" /><Hidden name="businessId" value={businessId} /><Hidden name="questionId" value={question.id} /><Hidden name="direction" value="DOWN" /><button aria-label="Move question down" className={compactButton} disabled={index === questions.length - 1 || questionPending}><ChevronDown className="size-5" /></button></form><button className={compactButton} aria-label="Edit question" onClick={() => setQuestionDialog({ mode: "edit", question })} type="button"><Pencil className="size-4" /></button><form action={questionAction} className="ml-auto"><Hidden name="action" value="SET_ACTIVE" /><Hidden name="businessId" value={businessId} /><Hidden name="questionId" value={question.id} /><Hidden name="isActive" value={!question.is_active} /><button className={`min-h-10 rounded-xl px-3 text-xs font-semibold ${question.is_active ? "bg-amber-50 text-amber-800" : "bg-emerald-50 text-emerald-800"}`} disabled={questionPending}>{question.is_active ? "Disable" : "Enable"}</button></form><button aria-label="Archive question" className="flex size-10 items-center justify-center rounded-xl bg-rose-50 text-rose-700" onClick={() => setArchiveQuestion(question)} type="button"><Archive className="size-4" /></button></div>
        <div className="mt-5 border-t border-slate-100 pt-4"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-slate-800">Answer options</h3><button className="flex min-h-10 items-center gap-1 rounded-xl bg-slate-900 px-3 text-xs font-semibold text-white disabled:opacity-40" disabled={question.options.length >= 6} onClick={() => openOption({ mode: "create", questionId: question.id })} type="button"><Plus className="size-4" />Add option</button></div>
          <div className="mt-3 space-y-2">{question.options.map((option, optionIndex) => <div className="flex items-center gap-2 rounded-2xl bg-slate-50 p-3" key={option.id}><div className="min-w-0 flex-1"><p className={`truncate text-sm font-medium ${option.is_active ? "text-slate-800" : "text-slate-400"}`}>{option.label}</p><p className="truncate text-xs text-slate-400">{option.value}</p></div><form action={optionAction}><Hidden name="action" value="MOVE" /><Hidden name="businessId" value={businessId} /><Hidden name="questionId" value={question.id} /><Hidden name="optionId" value={option.id} /><Hidden name="direction" value="UP" /><button aria-label="Move option up" className={compactButton} disabled={optionIndex === 0 || optionPending}><ChevronUp className="size-4" /></button></form><form action={optionAction}><Hidden name="action" value="MOVE" /><Hidden name="businessId" value={businessId} /><Hidden name="questionId" value={question.id} /><Hidden name="optionId" value={option.id} /><Hidden name="direction" value="DOWN" /><button aria-label="Move option down" className={compactButton} disabled={optionIndex === question.options.length - 1 || optionPending}><ChevronDown className="size-4" /></button></form><button aria-label="Edit option" className={compactButton} onClick={() => openOption({ mode: "edit", questionId: question.id, option })} type="button"><Pencil className="size-4" /></button><form action={optionAction}><Hidden name="action" value="SET_ACTIVE" /><Hidden name="businessId" value={businessId} /><Hidden name="questionId" value={question.id} /><Hidden name="optionId" value={option.id} /><Hidden name="isActive" value={!option.is_active} /><button className={`min-h-10 rounded-xl px-2 text-[0.7rem] font-semibold ${option.is_active ? "bg-white text-slate-600" : "bg-emerald-100 text-emerald-700"}`} disabled={optionPending}>{option.is_active ? "Disable" : "Enable"}</button></form></div>)}</div>
        </div>
      </article>;
    })}</div>}
    {questions.length ? <button className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl border border-dashed border-slate-300 bg-white text-sm font-semibold text-slate-700" onClick={() => setQuestionDialog({ mode: "create" })} type="button"><Plus className="size-5" />Add question</button> : null}

    {questionDialog ? <div className="fixed inset-0 z-50 flex items-end bg-slate-950/45 p-3 sm:items-center sm:justify-center"><section className="w-full rounded-[1.75rem] bg-white p-5 shadow-2xl sm:max-w-md" role="dialog" aria-modal="true"><div className="flex justify-between"><h2 className="text-xl font-semibold">{questionDialog.mode === "create" ? "Add question" : "Edit question"}</h2><button className="flex size-10 items-center justify-center rounded-full bg-slate-100" onClick={() => setQuestionDialog(null)}><X className="size-5" /></button></div><form action={questionAction} className="mt-5" onSubmit={() => setQuestionDialog(null)}><Hidden name="action" value={questionDialog.mode === "create" ? "CREATE" : "UPDATE"} /><Hidden name="businessId" value={businessId} />{questionDialog.mode === "edit" ? <Hidden name="questionId" value={questionDialog.question.id} /> : null}<label className="text-sm font-semibold text-slate-800">Question<textarea className="mt-2 min-h-28 w-full rounded-2xl border border-slate-300 p-4 text-base outline-none focus:border-emerald-600" defaultValue={questionDialog.mode === "edit" ? questionDialog.question.question : ""} maxLength={300} name="question" required /></label><p className="mt-2 text-xs text-slate-500">New questions start inactive. Add at least two active options before enabling.</p><button className="mt-5 min-h-12 w-full rounded-2xl bg-emerald-700 text-sm font-semibold text-white" disabled={questionPending}>{questionPending ? <LoaderCircle className="mx-auto size-5 animate-spin" /> : "Save question"}</button></form></section></div> : null}

    {optionDialog ? <div className="fixed inset-0 z-50 flex items-end bg-slate-950/45 p-3 sm:items-center sm:justify-center"><section className="w-full rounded-[1.75rem] bg-white p-5 shadow-2xl sm:max-w-md" role="dialog" aria-modal="true"><div className="flex justify-between"><h2 className="text-xl font-semibold">{optionDialog.mode === "create" ? "Add option" : "Edit option"}</h2><button className="flex size-10 items-center justify-center rounded-full bg-slate-100" onClick={() => setOptionDialog(null)}><X className="size-5" /></button></div><form action={optionAction} className="mt-5 space-y-4" onSubmit={() => setOptionDialog(null)}><Hidden name="action" value={optionDialog.mode === "create" ? "CREATE" : "UPDATE"} /><Hidden name="businessId" value={businessId} /><Hidden name="questionId" value={optionDialog.questionId} />{optionDialog.mode === "edit" ? <Hidden name="optionId" value={optionDialog.option.id} /> : <Hidden name="isActive" value="true" />}<label className="block text-sm font-semibold text-slate-800">Label<input className="mt-2 min-h-12 w-full rounded-2xl border border-slate-300 px-4 text-base" maxLength={160} name="label" onChange={(event) => { setOptionLabel(event.target.value); if (!valueEdited) setOptionValue(optionValueFromLabel(event.target.value)); }} required value={optionLabel} /></label><label className="block text-sm font-semibold text-slate-800">Value<input className="mt-2 min-h-12 w-full rounded-2xl border border-slate-300 px-4 text-base" maxLength={160} name="value" onChange={(event) => { setValueEdited(true); setOptionValue(event.target.value.toLowerCase()); }} required value={optionValue} /></label><button className="min-h-12 w-full rounded-2xl bg-emerald-700 text-sm font-semibold text-white" disabled={optionPending}>{optionPending ? <LoaderCircle className="mx-auto size-5 animate-spin" /> : "Save option"}</button></form></section></div> : null}

    {archiveQuestion ? <div className="fixed inset-0 z-50 flex items-end bg-slate-950/45 p-3 sm:items-center sm:justify-center"><section className="w-full rounded-[1.75rem] bg-white p-5 shadow-2xl sm:max-w-md" role="dialog" aria-modal="true"><h2 className="text-xl font-semibold text-slate-950">Archive question?</h2><p className="mt-2 text-sm leading-6 text-slate-600">It will be disabled and removed from management and preview while remaining stored for history.</p><form action={questionAction} className="mt-6 grid grid-cols-2 gap-3" onSubmit={() => setArchiveQuestion(null)}><Hidden name="action" value="ARCHIVE" /><Hidden name="businessId" value={businessId} /><Hidden name="questionId" value={archiveQuestion.id} /><button className="min-h-12 rounded-2xl border border-slate-300 text-sm font-semibold" onClick={() => setArchiveQuestion(null)} type="button">Cancel</button><button className="min-h-12 rounded-2xl bg-rose-700 text-sm font-semibold text-white">Archive</button></form></section></div> : null}
  </div>;
}
